name : helloGithubAction

on : [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 파일 목록 출력!!
      run: ls -al
    - name: 파이썬 패키치 확인!!
      run: pip list
    - name: pip 업그레이드!!
      run: python -m pip install --upgrade pip    
    - name: pip 인스톨!!
      run: pip install -r requiments.txt    
    - name: 파이썬 실행!!
      run: python test.py      
